---
builds:
  - id: ggql
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: ggql
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/ggql/ggql/config.Build={{.Date}} -X github.com/ggql/ggql/config.Version={{.Version}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
